---
- name: Restart Promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
