version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/terraform/aws"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform/hetzner"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform/cloudflare"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform/grafana"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
