all:
  hosts:
    dreamseed:
      ansible_host: 178.104.138.158
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /Users/Vitali_Kuts/.ssh/Vitali.pem
      ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
      server_ip: 178.104.138.158
