---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Grafana
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
