---
- name: Restart Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: Restart Apache Exporter
  ansible.builtin.systemd:
    name: apache_exporter
    state: restarted

- name: Restart Nginx Exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted

- name: Restart MySQL Exporter
  ansible.builtin.systemd:
    name: mysqld_exporter
    state: restarted

- name: Restart VictoriaMetrics
  ansible.builtin.systemd:
    name: victoria-metrics
    state: restarted