#!/bin/bash
set -euo pipefail

CONFIG="/etc/nginx/conf.d/cloudflare-realip.conf"
TMP=$(mktemp /tmp/cloudflare-realip.XXXXXX)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" << 'HEADER'
# Cloudflare real IP ranges — auto-generated by update_cloudflare_ips.sh
# Source: https://www.cloudflare.com/ips-v4 / ips-v6
HEADER

curl -s https://www.cloudflare.com/ips-v4 | while read ip; do
  echo "set_real_ip_from $ip;" >> "$TMP"
done

curl -s https://www.cloudflare.com/ips-v6 2>/dev/null | while read ip; do
  echo "set_real_ip_from $ip;" >> "$TMP"
done

echo "real_ip_header CF-Connecting-IP;" >> "$TMP"

if ! diff "$CONFIG" "$TMP" >/dev/null 2>&1; then
  cp "$TMP" "$CONFIG"
  echo "[$(date)] Updated cloudflare IPs ($(grep -c 'set_real_ip_from' "$CONFIG") ranges)" >> /var/log/cloudflare-ips-update.log
  nginx -t 2>/dev/null && systemctl reload nginx && echo "  nginx reloaded" >> /var/log/cloudflare-ips-update.log
fi
