---
- name: Set Apache Exporter desired version
  ansible.builtin.set_fact:
    monitoring_ae_version: "{{ monitoring_apache_version }}"

- name: Check if Apache Exporter is installed
  ansible.builtin.stat:
    path: /usr/local/bin/apache_exporter
  register: monitoring_ae_bin

- name: Get current Apache Exporter version
  ansible.builtin.command: /usr/local/bin/apache_exporter --version
  changed_when: false
  failed_when: false
  register: monitoring_ae_current_version
  when: monitoring_ae_bin.stat.exists

- name: Install/Upgrade Apache Exporter
  when: >
    not monitoring_ae_bin.stat.exists or
    monitoring_ae_version not in (monitoring_ae_current_version.stdout | default(''))
  block:
    - name: Download Apache Exporter
      ansible.builtin.get_url:
        url: "https://github.com/Lusitaniae/apache_exporter/releases/download/v{{ monitoring_ae_version }}/apache_exporter-{{ monitoring_ae_version }}.linux-amd64.tar.gz"
        dest: /tmp/apache_exporter.tar.gz
        mode: "0644"

    - name: Extract Apache Exporter
      ansible.builtin.unarchive:
        src: /tmp/apache_exporter.tar.gz
        dest: /tmp/
        remote_src: true

    - name: Install Apache Exporter binary
      ansible.builtin.copy:
        src: "/tmp/apache_exporter-{{ monitoring_ae_version }}.linux-amd64/apache_exporter"
        dest: /usr/local/bin/apache_exporter
        mode: "0755"
        remote_src: true

    - name: Cleanup Apache Exporter temp files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/apache_exporter.tar.gz
        - "/tmp/apache_exporter-{{ monitoring_ae_version }}.linux-amd64"

- name: Create apache_exporter user
  ansible.builtin.user:
    name: apache_exporter
    system: true
    create_home: false
    shell: /bin/false

- name: Deploy Apache Exporter service
  ansible.builtin.copy:
    dest: /etc/systemd/system/apache_exporter.service
    content: |
      [Unit]
      Description=Apache Exporter
      After=network.target

      [Service]
      Type=simple
      User=apache_exporter
      ExecStart=/usr/local/bin/apache_exporter --web.listen-address=127.0.0.1:9117 --scrape_uri=http://127.0.0.1:80/server-status?auto
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  notify: Restart Apache Exporter