---
- name: Upload check_site.sh
  ansible.builtin.template:
    src: check_site.sh.j2
    dest: /usr/local/bin/check_site.sh
    mode: "0755"
  become: true

- name: Deploy check_site systemd timer
  ansible.builtin.template:
    src: check-site.timer.j2
    dest: /etc/systemd/system/check-site.timer
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload systemd
  when: monitoring_cron_enabled | bool

- name: Deploy check_site systemd service
  ansible.builtin.template:
    src: check-site.service.j2
    dest: /etc/systemd/system/check-site.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload systemd
  when: monitoring_cron_enabled | bool

- name: Enable and start check_site timer
  ansible.builtin.systemd:
    name: check-site.timer
    state: started
    enabled: true
  become: true
  when: monitoring_cron_enabled | bool
