---
- name: Install/Upgrade MySQL Exporter
  ansible.builtin.include_tasks: _install_binary.yml
  vars:
    monitor_bin_name: mysqld_exporter
    monitor_bin_path: /usr/local/bin/mysqld_exporter
    monitor_version: "{{ monitoring_mysql_version }}"
    monitor_download_url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ monitoring_mysql_version }}/mysqld_exporter-{{ monitoring_mysql_version }}.linux-amd64.tar.gz"
    monitor_extracted_binary: "/tmp/mysqld_exporter-{{ monitoring_mysql_version }}.linux-amd64/mysqld_exporter"

- name: Create mysqld_exporter user
  ansible.builtin.user:
    name: mysqld_exporter
    system: true
    create_home: false
    shell: /bin/false
  become: true

- name: Create .my.cnf for exporter in system location
  ansible.builtin.copy:
    dest: /etc/mysqld_exporter.cnf
    content: |
      [client]
      user = monitoring
      password = {{ db_pass }}
    owner: mysqld_exporter
    group: mysqld_exporter
    mode: "0600"
  become: true
  when: db_pass | default('') | length > 0
  no_log: true

- name: Deploy MySQL Exporter service
  ansible.builtin.copy:
    dest: /etc/systemd/system/mysqld_exporter.service
    content: |
      [Unit]
      Description=MySQL Exporter
      After=network.target mariadb.service

      [Service]
      Type=simple
      User=mysqld_exporter
      ExecStart=/usr/local/bin/mysqld_exporter --config.my-cnf=/etc/mysqld_exporter.cnf --web.listen-address=127.0.0.1:9104 --no-collect.slave_status
      Restart=always
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  become: true
  notify: Restart MySQL Exporter
