---
- name: Set MySQL Exporter desired version
  ansible.builtin.set_fact:
    monitoring_mysql_version: "{{ monitoring_mysql_version }}"

- name: Check if MySQL Exporter is installed
  ansible.builtin.stat:
    path: /usr/local/bin/mysqld_exporter
  register: monitoring_mysql_bin

- name: Get current MySQL Exporter version
  ansible.builtin.command: /usr/local/bin/mysqld_exporter --version
  changed_when: false
  failed_when: false
  register: monitoring_mysql_current_version
  when: monitoring_mysql_bin.stat.exists

- name: Install/Upgrade MySQL Exporter
  when: >
    not monitoring_mysql_bin.stat.exists or
    monitoring_mysql_version not in (monitoring_mysql_current_version.stdout | default(''))
  block:
    - name: Download MySQL Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ monitoring_mysql_version }}/mysqld_exporter-{{ monitoring_mysql_version }}.linux-amd64.tar.gz"
        dest: /tmp/mysqld_exporter.tar.gz
        mode: "0644"

    - name: Extract MySQL Exporter
      ansible.builtin.unarchive:
        src: /tmp/mysqld_exporter.tar.gz
        dest: /tmp/
        remote_src: true

    - name: Install MySQL Exporter binary
      ansible.builtin.copy:
        src: "/tmp/mysqld_exporter-{{ monitoring_mysql_version }}.linux-amd64/mysqld_exporter"
        dest: /usr/local/bin/mysqld_exporter
        mode: "0755"
        remote_src: true

    - name: Cleanup MySQL Exporter temp files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/mysqld_exporter.tar.gz
        - "/tmp/mysqld_exporter-{{ monitoring_mysql_version }}.linux-amd64"

- name: Create mysqld_exporter user
  ansible.builtin.user:
    name: mysqld_exporter
    system: true
    create_home: false
    shell: /bin/false

- name: Create .my.cnf for exporter in system location
  ansible.builtin.copy:
    dest: /etc/mysql/conf.d/exporter.cnf
    content: |
      [client]
      user = monitoring
      password = {{ db_pass }}
    owner: mysqld_exporter
    group: mysqld_exporter
    mode: "0600"
  when: db_pass | default('') | length > 0
  no_log: true

- name: Deploy MySQL Exporter service
  ansible.builtin.copy:
    dest: /etc/systemd/system/mysqld_exporter.service
    content: |
      [Unit]
      Description=MySQL Exporter
      After=network.target mariadb.service

      [Service]
      Type=simple
      User=mysqld_exporter
      ExecStart=/usr/local/bin/mysqld_exporter --config.my-cnf=/etc/mysql/conf.d/exporter.cnf --web.listen-address=127.0.0.1:9104 --no-collect.slave_status
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  notify: Restart MySQL Exporter