---
- name: Install/Upgrade Nginx Exporter
  vars:
    _exp_name: "Nginx Exporter"
    bin: nginx-prometheus-exporter
    version: "{{ monitoring_nginx_version }}"
    url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ monitoring_nginx_version }}/nginx-prometheus-exporter_{{ monitoring_nginx_version }}_linux_amd64.tar.gz"
    src_in_tmp: /tmp/nginx-prometheus-exporter
    cleanup_dirs:
      - "/tmp/{{ bin }}.tar.gz"
      - /tmp/nginx-prometheus-exporter
  ansible.builtin.include_tasks: _install_binary.yml

- name: Create nginx_exporter user
  ansible.builtin.user:
    name: nginx_exporter
    system: true
    create_home: false
    shell: /bin/false

- name: Deploy Nginx Exporter service
  ansible.builtin.copy:
    dest: /etc/systemd/system/nginx_exporter.service
    content: |
      [Unit]
      Description=Nginx Prometheus Exporter
      After=network.target nginx.service

      [Service]
      Type=simple
      User=nginx_exporter
      ExecStart=/usr/local/bin/nginx-prometheus-exporter --web.listen-address=127.0.0.1:9113 --nginx.scrape-uri=http://127.0.0.1:80/nginx_status
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  notify: Restart Nginx Exporter