---
- name: Install/Upgrade Node Exporter
  ansible.builtin.include_tasks: _install_binary.yml
  vars:
    monitor_bin_name: node_exporter
    monitor_bin_path: /usr/local/bin/node_exporter
    monitor_version: "{{ monitoring_node_version }}"
    monitor_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ monitoring_node_version }}/node_exporter-{{ monitoring_node_version }}.linux-amd64.tar.gz"
    monitor_extracted_binary: "/tmp/node_exporter-{{ monitoring_node_version }}.linux-amd64/node_exporter"

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    system: true
    create_home: false
    shell: /bin/false

- name: Deploy Node Exporter service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
  notify: Restart Node Exporter