---
- name: Install/Upgrade Redis Exporter
  ansible.builtin.include_tasks: _install_binary.yml
  vars:
    monitor_bin_name: redis_exporter
    monitor_bin_path: /usr/local/bin/redis_exporter
    monitor_version: "{{ monitoring_redis_version }}"
    monitor_download_url: "https://github.com/oliver006/redis_exporter/releases/download/v{{ monitoring_redis_version }}/redis_exporter-v{{ monitoring_redis_version }}.linux-amd64.tar.gz"
    monitor_extracted_binary: "/tmp/redis_exporter-v{{ monitoring_redis_version }}.linux-amd64/redis_exporter"

- name: Create redis_exporter user
  ansible.builtin.user:
    name: redis_exporter
    system: true
    create_home: false
    shell: /bin/false
  become: true

- name: Deploy Redis Exporter service
  ansible.builtin.copy:
    dest: /etc/systemd/system/redis_exporter.service
    content: |
      [Unit]
      Description=Redis Exporter
      After=network.target redis-server.service

      [Service]
      Type=simple
      User=redis_exporter
      Environment=REDIS_PASSWORD={{ redis_password }}
      ExecStart=
      ExecStart=/usr/local/bin/redis_exporter -redis.addr 127.0.0.1:6379{% if redis_password | length > 0 %} -redis.password ${REDIS_PASSWORD}{% endif %} -web.listen-address 127.0.0.1:9121
      Restart=always
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  become: true
  notify: Restart Redis Exporter
