---
- name: Install/Upgrade VictoriaMetrics
  vars:
    _exp_name: VictoriaMetrics
    bin: victoria-metrics
    version: "{{ monitoring_vm_version }}"
    url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ monitoring_vm_version }}/victoria-metrics-linux-amd64-v{{ monitoring_vm_version }}.tar.gz"
    src_in_tmp: /tmp/victoria-metrics-prod
    cleanup_dirs:
      - /tmp/victoria-metrics.tar.gz
      - /tmp/victoria-metrics-prod
  ansible.builtin.include_tasks: _install_binary.yml

- name: Create victoria-metrics user
  ansible.builtin.user:
    name: victoria-metrics
    system: true
    create_home: false
    shell: /bin/false

- name: Create VictoriaMetrics directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    mode: "0755"
  loop:
    - {path: /var/lib/victoria-metrics, owner: victoria-metrics}
    - {path: /etc/victoria-metrics, owner: root}

- name: Deploy VictoriaMetrics scrape config
  ansible.builtin.template:
    src: scrape.yml.j2
    dest: /etc/victoria-metrics/scrape.yml
    mode: "0644"
  notify: Restart VictoriaMetrics

- name: Deploy VictoriaMetrics service
  ansible.builtin.template:
    src: victoria-metrics.service.j2
    dest: /etc/systemd/system/victoria-metrics.service
    mode: "0644"
  notify: Restart VictoriaMetrics