---
- name: Install Apache packages
  become: true
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-brotli
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
