---
- name: 02 Web Server (Nginx/Apache + PHP + SSL)
  hosts: dreamseed
  become: false
  gather_facts: true

  roles:
    - role: nginx
      when: web_server == "nginx"
    - role: apache_http
      when: web_server == "apache"
    - ssl
    - role: nginx-ssl
      when: web_server == "nginx"
    - role: apache_ssl
      when: web_server == "apache"
    - redis
    - php
    - cloudflare_cache
