{
 "title": "Nginx",
 "description": "Dashboard for Nginx Web Server",
 "tags": [ "Nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nginx_connections_active{job=\"nginx\"}, instance)"
   },
   {
    "name": "node_instance",
    "label": "Node Instance",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=~\"$node_instance\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current CPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=~\"$node_instance\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node_instance\"} - node_memory_MemAvailable_bytes{instance=~\"$node_instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0|ens.*\",instance=~\"$node_instance\"}[5m])",
     "legendFormat": "net_bytes_recv"
    },
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{instance=~\"$node_instance\"}[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  },
  {
   "title": "Network Ouput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth0|ens.*\",instance=~\"$node_instance\"}[5m])",
     "legendFormat": "net_bytes_sent"
    },
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{instance=~\"$node_instance\"}[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  },
  { "title": "Nginx Requests Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Response 2XX / 5m",
   "type": "graph",
   "description": "Requests with 200 Status Code",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Response 200 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 200 response by nginx server",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total{instance=~\"$instance\"}[24h])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Response 4XX  /5m",
   "type": "graph",
   "description": "Requests with 4XX Status Code",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Response 404 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 404 response from nginx server",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Response 3XX",
   "type": "graph",
   "description": "Requests with 3XX Status Code",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response 5XX",
   "type": "graph",
   "description": "Requests with 5XX Status Code",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request 503 Resonse",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Nginx Connections Accepted",
   "type": "graph",
   "description": "The total number of accepted connections from clients since the nginx master process started. Note that reloading configurations or restarting worker processes will not reset this metric. If you terminate and restart the master process, you will reset the metric.\n\n",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_accepted{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Writing",
   "type": "stat",
   "description": "The current number of connections from clients where nginx is writing a response back to the client.\n",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Active Connections[accepted]",
   "type": "bargauge",
   "description": "The current number of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance }}"
    }
   ]
  },
  {
   "title": "Nginx Waiting Connections",
   "type": "stat",
   "description": "The current number of connections from clients that are in the Idle / Waiting state.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Handled Request",
   "type": "graph",
   "description": "The total number of handled connections from clients since the nginx master process started. This will be lower than accepted only in cases where a connection is dropped before it is handled.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_handled{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Requests",
   "type": "graph",
   "description": "The total number of client requests since the nginx master process started. A request is an application-level (HTTP, etc.) event. It occurs when a client requests a resource via the application protocol. A single connection can (and often does) make many requests. So most of the time, there are more requests than accepted/handled connections.",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_requests_total{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "nginx_reading",
   "type": "stat",
   "description": "The current number of (accepted) connections from clients where nginx is reading the request. Measured at the time the status module was queried.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Each Request Detail",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=~\"$instance\"}[5m])"
    }
   ]
  }
 ]
}